// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SchoolManagement.DbInfrastructure.Context;

#nullable disable

namespace SchoolManagement.DbInfrastructure.Migrations
{
    [DbContext(typeof(SchoolManagementDbContext))]
    [Migration("20260331000000_AddSchoolApprovalRequestAndOrgApprovalFields")]
    partial class AddSchoolApprovalRequestAndOrgApprovalFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Target model snapshot is maintained in SchoolManagementDbContextModelSnapshot.cs
        }
    }
}
