// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SchoolManagement.DbInfrastructure.Context;

#nullable disable

namespace SchoolManagement.DbInfrastructure.Migrations;

[DbContext(typeof(SchoolManagementDbContext))]
[Migration("20260331180000_AddOrgStorageMailConfig")]
partial class AddOrgStorageMailConfig
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // Designer file intentionally minimal — full model is in ModelSnapshot.
    }
}
